services:
  api:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
      # - ./logs:/app/logs # esto para publicar, pero para dev montamos toda la app
    restart: unless-stopped  # Reinicia el contenedor a menos que se detenga manualmente
