services:
  api:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app                # para desarrollo
      - ./logs:/app/logs
    # restart: unless-stopped   # Reinicia el contenedor a menos que se detenga manualmente
